//@author Naufal Ulinnuha
public class HitungBidang extends javax.swing.JFrame {

    /**
     * Creates new form HitungBidang
     */
    public HitungBidang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuPersegiPanjang = new javax.swing.JMenuItem();
        MenuLingkaran = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("BIDANG 2 DIMENSI");

        jMenu1.setText("Bidang");

        MenuPersegiPanjang.setText("Persegi Panjang");
        MenuPersegiPanjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenuPersegiPanjangMouseReleased(evt);
            }
        });
        MenuPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPersegiPanjangActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPersegiPanjang);

        MenuLingkaran.setText("Lingkaran");
        MenuLingkaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenuLingkaranMouseReleased(evt);
            }
        });
        MenuLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLingkaranActionPerformed(evt);
            }
        });
        jMenu1.add(MenuLingkaran);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPersegiPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPersegiPanjangActionPerformed

    private void MenuLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLingkaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuLingkaranActionPerformed

    private void MenuPersegiPanjangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPersegiPanjangMouseReleased
        BidangPersegiPanjang BPP = new BidangPersegiPanjang();
        BPP.setLocationRelativeTo(this);
        BPP.setVisible(true);
    }//GEN-LAST:event_MenuPersegiPanjangMouseReleased

    private void MenuLingkaranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLingkaranMouseReleased
        BidangLingkaran BL = new BidangLingkaran();
        BL.setLocationRelativeTo(this);
        BL.setVisible(true);
    }//GEN-LAST:event_MenuLingkaranMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitungBidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitungBidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitungBidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitungBidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitungBidang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuLingkaran;
    private javax.swing.JMenuItem MenuPersegiPanjang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
